os: linux


language: java
services:
  - docker
cache: bundler
dist: bionic


install: skip

jobs:
  include:
    - name: failing
      script: main.java

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
  
